language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
    env: BUILD_SDIST=true
install:
- pip install -r requirements.txt
script:
- python test/__init__.py
before_deploy: echo $TRAVIS_TAG | sed 's/^.//' > version.txt
deploy:
  skip_cleanup: true
  provider: pypi
  user: qta
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ v[0-9]+\\.[0-9]+\\.[0-9]+ && $BUILD_SDIST=true"
  password:
    secure: GilIkyLjYNvhDKOtnCExA9yLLGgZcwb1Tp+dmj+cd6345rXMNsg1uT421aKpc8ZvfLawWHsiLkvxd1eHbSbFlV1M3VriZr1Wwq8Zi96iME3fMPFkXNA76DSNHQJ9o47G7XYSKyNoAcqG+bpdFqH867SuoH3/bVvtcwp+luWlUn9Vn0jrw8TIFqIBEOYxKfmfnE6UiQOuNoIqsB6KE1Z4kB3e0xIWtQx1TrFm+3T57cdBviDtdNMwkEKn7GXDYdLx9pkFMTJYamYOFmZV54ADBT+vDxJN7mk4CTozBpZ6jojIP3PBKmLejYlvFXnwThmOx4tIGS2hmE/Psf1CfRIVKsC2GA7ePJScw6YpvBH6NO7YXXeztjnH7rSzpt+5s4vZVVvfTTRk9D8vH0Y2HmHfgKFY64RYvNPbToGdmIoVL2dZIRoXv9c8sDL1rNlWotdGuyroAOO91W/BF5aYl/+5HjyOaBaTGypSadCwOTvUeMANq16peHd1StHAnw7yZZ0FXFEsNToyJ3ktsvXQ3yTQKhFsN3rI6dK1wXdMEWredRGVcFZ+gUOk4R649WhzY/NyAaptI86qb5GrP+hyCzPZEra/KF07giygRnxBlH4XLZJT1p63tctbWes/JB63UPHb8s/9e8JjE0I76/aGzhgcHk67KqK1lNeHXMDDfYk2+W0=
